### Minix Neo U1 onboard audio via Optical SPDIF
### Operating System: Armbian Bookworm 64bit
### Official docker version 25.0.1

### I also had to:
###   add `abi.cp15_barrier=2` to `/etc/sysctl.conf` in order to suppress lots of warnings
###   install avahi-daemon using `sudo apt-get install avahi-daemon`

### Performance is poor due to emulation issues of 32bit -> audio quality is also really bad for this reason
### With other audio containers, there are no issues as long as this tidal-connect is turned off

pcm.custom {
  type plug
  slave.pcm {
    type hw
    card VEGAS95
    device 1
  }
}
