---
version: '3'

services:
  tidal-connect:
    image: edgecrush3r/tidal-connect:latest
    container_name: tidal-connect
    tty: true
    network_mode: host
    devices:
     - /dev/snd
    environment:
     - CARD_NAME=${CARD_NAME}
     - CARD_INDEX=${CARD_INDEX:--1}
     - FRIENDLY_NAME=${FRIENDLY_NAME:-tidal-connect}
     - MODEL_NAME=${MODEL_NAME:-RaspberryPi}
     - MQA_CODEC=${MQA_CODEC:-false}
     - MQA_PASSTHROUGH=${MQA_PASSTHROUGH:-true}
     - SLEEP_TIME_SEC=${SLEEP_TIME:-3}
    volumes:
      - ./bin/entrypoint.sh:/entrypoint.sh
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
