---
version: '3'

services:
  tidal-connect:
    image: edgecrush3r/tidal-connect:latest
    container_name: tidal-connect
    tty: true
    network_mode: host
    devices:
     - /dev/snd
    environment:
     - CARD_NAME=${CARD_NAME:-}
     - CARD_INDEX=${CARD_INDEX:-}
     - CARD_DEVICE=${CARD_DEVICE:-}
     - CARD_FORMAT=${CARD_FORMAT:-}
     - CREATED_ASOUND_CARD_NAME=${CREATED_ASOUND_CARD_NAME:-}
     - ENABLE_SOFTVOLUME=${ENABLE_SOFTVOLUME:-yes}
     - ENABLE_GENERATED_TONE=${ENABLE_GENERATED_TONE:-yes}
     - ASOUND_FILE_PREFIX=${ASOUND_FILE_PREFIX:-}
     - FRIENDLY_NAME=${FRIENDLY_NAME:-TIDAL connect}
     - MODEL_NAME=${MODEL_NAME:-Audio Streamer}
     - MQA_CODEC=${MQA_CODEC:-false}
     - MQA_PASSTHROUGH=${MQA_PASSTHROUGH:-false}
     - FORCE_PLAYBACK_DEVICE=${FORCE_PLAYBACK_DEVICE:-}
     - SLEEP_TIME_SEC=${SLEEP_TIME:-3}
     - RESTART_ON_FAIL=${RESTART_ON_FAIL:-1}
     - RESTART_WAIT_SEC=${RESTART_WAIT_SEC:-30}
    volumes:
     - ./assets:/assets:ro
     - ./userconfig:/userconfig:ro
     - ./bin/common.sh:/common.sh
     - ./bin/entrypoint.sh:/entrypoint.sh
     - /var/run/dbus:/var/run/dbus
    dns:
      - ${DNS_SERVER_LIST:-8.8.8.8 8.8.4.4}
    restart: unless-stopped
